Top2000/Models/Song.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top2000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.Lijst = new HashSet<Lijst>();
        }
    
        public int songid { get; set; }
        public int artiestid { get; set; }
        public string titel { get; set; }
        public Nullable<int> jaar { get; set; }
    
        public virtual Artiest Artiest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lijst> Lijst { get; set; }
    }
}

Top2000/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Top2000.Models;

namespace Top2000.Controllers
{
    public class SongsController : Controller
    {
        private Top2000Entities1 db = new Top2000Entities1();

        // GET: Songs
        public ActionResult Index(string search)
        {
            var song = db.Song.Include(s => s.Artiest);
            return View(song.Where(x => x.titel.StartsWith(search) || search == null).ToList());
        }

        // GET: Songs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = db.Song.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            return View(song);
        }

        // GET: Songs/Create
        public ActionResult Create()
        {
            ViewBag.artiestid = new SelectList(db.Artiest, "Artiestid", "naam");
            return View();
        }

        // POST: Songs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "songid,artiestid,titel,jaar")] Song song)
        {
            if (ModelState.IsValid)
            {
                db.Song.Add(song);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.artiestid = new SelectList(db.Artiest, "Artiestid", "naam", song.artiestid);
            return View(song);
        }

        // GET: Songs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = db.Song.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            ViewBag.artiestid = new SelectList(db.Artiest, "Artiestid", "naam", song.artiestid);
            return View(song);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "songid,artiestid,titel,jaar")] Song song)
        {
            if (ModelState.IsValid)
            {
                db.Entry(song).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.artiestid = new SelectList(db.Artiest, "Artiestid", "naam", song.artiestid);
            return View(song);
        }

        // GET: Songs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Song song = db.Song.Find(id);
            if (song == null)
            {
                return HttpNotFound();
            }
            return View(song);
        }

        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Song song = db.Song.Find(id);
            db.Song.Remove(song);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Top2000/Views/Songs/Create.cshtml
@model Top2000.Models.Song

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Song</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.artiestid, "artiestid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("artiestid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.artiestid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.titel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jaar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jaar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jaar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Top2000/Views/Songs/Delete.cshtml
@model Top2000.Models.Song

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Song</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jaar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jaar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Artiest.naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artiest.naam)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Top2000/Views/Songs/Details.cshtml
@model Top2000.Models.Song

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Song</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.titel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jaar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jaar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Artiest.naam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artiest.naam)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.songid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Top2000/Views/Songs/Edit.cshtml
@model Top2000.Models.Song

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Song</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.songid)

        <div class="form-group">
            @Html.LabelFor(model => model.artiestid, "artiestid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("artiestid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.artiestid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.titel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.titel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.titel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.jaar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jaar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jaar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Top2000/Views/Songs/Index.cshtml
@model IEnumerable<Top2000.Models.Song>

@{
    ViewBag.Title = "Index";
}

<h2>Artiesten Info</h2>

@using (Html.BeginForm("Index", "Songs", FormMethod.Get))
{
    @Html.TextBox("Search") <input type="submit" value="Search" hidden="hidden"/>
}

<table class="table">
    <tr>
        <th>Titel</th>
        <th>Jaar</th>
        <th>Artiest / Band</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @if (item.Artiest.naam == "Queen")
        {
        <td>
            @Html.DisplayFor(modelItem => item.titel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.jaar)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Artiest.naam)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.songid }) |
            @Html.ActionLink("Details", "Details", new { id = item.songid }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.songid })
        </td>
        }
    </tr>
}

</table>